name = "pipedrive-field-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "a0c4c927bfaca2b4ccf02338e3a73459"

# PIPEDRIVE_API_TOKEN is stored as a secret.
# Set it with: npx wrangler secret put PIPEDRIVE_API_TOKEN
